

DBCC CHECKIDENT ('NhanVien', RESEED, 1);  
GO
DBCC CHECKIDENT ('KhachHang', RESEED, 1);  
GO
DBCC CHECKIDENT ('TaiKhoan', RESEED, 1);  
GO
DBCC CHECKIDENT ('HoaDonThanhToan', RESEED, 1);  
GO
DBCC CHECKIDENT ('MonAn', RESEED, 1);  
GO
DBCC CHECKIDENT ('ChuDe', RESEED, 1);  
GO
DBCC CHECKIDENT ('KhachVangLai', RESEED, 1);  
GO
DBCC CHECKIDENT ('KhuyenMai', RESEED, 1);  
GO