//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int MaHoaDon { get; set; }
        public int MaMonAn { get; set; }
        public int SoLuong { get; set; }
    
        public virtual HoaDonThanhToan HoaDonThanhToan { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
